### ISSUE TITLE
generic ticket template error on css

### ISSUE THREAD

**Issue by empereira** [glpi-project/doc#100]
hi,

In tests performed, it seems to me that the css class TicketTask is not being applied.

When it is for a new follow-up, it works.
![Captura de tela_2022-06-02_13-17-41](https://user-images.githubusercontent.com/29874574/171677551-29ec4d87-9503-4216-ad66-808d5a25aca1.png)

When it is for a task, it does not.
![Captura de tela_2022-06-02_13-19-01](https://user-images.githubusercontent.com/29874574/171677613-c3716de8-f287-4142-81e1-f30b8d754675.png)

I only copied and pasted the codes.

Any ideas?

**Comment by trasher** [comment]
Does not seems related to duocumentation
