### ISSUE TITLE
Missing documentation about php console to enable translation cache with Redis

### ISSUE THREAD

**Issue by gyto6** [glpi-project/doc#107]
The old way to simply add core values within glpi_configs is no more functionnal with GLPI 10.

You must now use the php bin/console cache:configure command to enable users data cache, but no instruction are given to enable the translation cache to work with Redis.

**Comment by cedric-anne** [comment]
Hi,

`translation` cache context is no more configurable in GLPI 10. When refactoring this part, I considered it was not necessary, but maybe I was wrong.

You can apply following patch:
```diff
diff --git a/src/Cache/CacheManager.php b/src/Cache/CacheManager.php
index 585e5092e5..c030bc425e 100644
--- a/src/Cache/CacheManager.php
+++ b/src/Cache/CacheManager.php
@@ -480,12 +480,11 @@ PHP;
      */
     public function isContextValid(string $context, bool $only_configurable = false): bool
     {
-        $core_contexts = ['core'];
+        $core_contexts = ['core', 'translations'];
 
         if (!$only_configurable) {
            // 'installer' and 'translations' cache storages cannot not be configured (they always use the filesystem storage)
             $core_contexts[] = 'installer';
-            $core_contexts[] = 'translations';
         }
 
         return in_array($context, $core_contexts, true) || preg_match('/^plugin:\w+$/', $context) === 1;
```

Then you will be able to configure the translation cache using following command:
`bin/console glpi:cache:configure --context=translations --dsn=redis://...`

Could you tell me how performances are improved ?

**Comment by gyto6** [comment]
Thanks !

The patch has been applied, the command is correct. It's whatever no more specified in the GUI that Redis is use for the translation cache.

Whatever, we've been migrating from 9.5 to 10, and users (about 300) claimed noticeable slowdown since th upgrade. I set back the Redis Users Data cache, which got desactivated.

I've been noticed that some improvements occured, but not as fast than 9.5. That's why I then posted as I set these two caches with Redis before.

Maybe that the graphical work GLPI 10 is the main "issue" here. I'll wait a week to to gather some feedback and tell you if the situation is better with this second cache set with Redis.

**Comment by cedric-anne** [comment]
We discussed about this in our steering committee and we all agree that giving control on translation cache configuration is not really necessary. It would not really change performances but will add some complexity that we do not want to introduce.
