### ISSUE TITLE
A word about opcache and TCPDF issues

### ISSUE THREAD

**Issue by trasher** [glpi-project/doc#21]
By default, font files from TCPDF will be loaded in the opcache... Causing oom restart quite often.

This happens mainly under some circumstances, but a word about that in the install docs may be usefull.

**Comment by remicollet** [comment]
for memory:
* opcache upstream default configuration is 128M
* 64M is usually largely enough for GLPI (lot of plugins may require more)
* tcpdf/fonts mays consume up to 90M (using users / prefs)
