### ISSUE TITLE
Convert .md files to .rst?

### ISSUE THREAD

**Issue by bzg** [glpi-project/doc#30]
Hi there. I've noticed there are many `.md` files left in the `source/` directory.

Would it help if I convert those file to `.rst`?  I plan to use [pandoc](https://pandoc.org/) for this task, and some proofreading would certainly be needed.

Let me know, thanks!

**Comment by trasher** [comment]
Hello,

It may indeed help, please open a pull request with that change so we can see. Thank you!

**Comment by bzg** [comment]
Thanks for the feedback! For the first PR, I plan to **replace** `.md` files by `.rst` files: it is okay or do you want to keep the `.md` files somewhere in the tree?

**Comment by trasher** [comment]
Yes, just replace them ;)

**Comment by bzg** [comment]
Hi, just a quick note to let you know I won't be able to work on this. Thanks for the feedback so far and good luck with enhancing the documentation.

**Comment by trasher** [comment]
Ok, no problem of course :) Thank you anyways!

**Comment by cconard96** [comment]
After the latest translation work, there are no more `.md` files in the documentation sources.
