### ISSUE TITLE
Documentation on new search engine 

### ISSUE THREAD

**Issue by nqb** [glpi-project/doc#5]
Hello,

Please add documentation on new search engine to understand which criterions are used.
![search_engine](https://cloud.githubusercontent.com/assets/10830260/15889621/24622f6e-2d6c-11e6-89fe-d836225d7f32.png)

Thanks !

**Comment by trasher** [comment]
Done already (http://glpi-user-documentation.readthedocs.io/fr/latest/premiers-pas/utiliser/rechercher.html#recherche-rapide)

**Comment by nqb** [comment]
Hello @trasher,

I notice that search engine find objets created by genericobject if you enable "Use Global search" for your type of object. 

Could you add a tip in this section that point to genericobject documentation ?

Thanks.
