### ISSUE TITLE
Don't understand how the help files / sites work 

### ISSUE THREAD

**Issue by Armin83** [glpi-project/doc#8]
Okay i read this below but i don't find a tools or docs dir outside from plugins or lib dir and i can't believe that this is located in lib.

> To test Markdown only copyt fr/en/image directories to daux/docs directory provide in tools

**Comment by trasher** [comment]
It's been a while I've not tried to build this version... As far as I remember; I found requirements on daux website (https://daux.io/).

Note that I've just updated the (stalled) master branch that switch to Sphinx/restructured text.
