### ISSUE TITLE
Rules for assigning an item to an entity

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/doc#81]
doc/source/modules/administration/rules/inventorytools.rst 
"A certain number of criteria are available: those containing generic fields (name, description, serial number, domain, IP address, subnet) but also fields coming from the inventory tool if the tool provides them."

but here is only one criteria - source

this criteria are in fusioninventory rules.

GLPI 9.5.6 
FusionInventory 9.5+3.0

**Comment by cconard96** [comment]
This version of the documentation is being built to match the features available in GLPI 10. It looks like the additional criteria options were added as part of the Native Inventory feature work and I confirmed that they show up in the GLPI version 10 RC releases.
